language: python
jobs:
  include:
    - stage: Tests
      name: Linting
      python: 3.8
      env: TOXENV=linting

    -
      python: 2.7
      env: TOXENV=py27

    -
      python: 3.6
      env: TOXENV=py36

    -
      python: 3.7
      env: TOXENV=py37

    -
      python: 3.8
      env: TOXENV=py38

    -
      python: pypy
      env: TOXENV=pypy

    -
      python: pypy3
      env: TOXENV=pypy3

    - stage: deploy
      python: 3.8
      install: skip
      script: skip
      deploy:
        provider: pypi
        user: davehunt
        password:
          secure: GLeh84BPqz7a8G6MywG72h/ddWMwXaot5R7kWfAOV/ZrErZ7l1lOEHf3IZ0AodPql+dsz9Ug1jAnNEpnozEVFzY5m9QON0VJORH5KgZjMIhZS5FOFEW24mEzJW6gejNk6vM0TFafj5iB/pwXNMSl3dQl4TX3+x31ARb2Ng/jrvrfDHoIdH6PYgcB0auS8JMryHBg54ObTb0KLsI4G6gRvnkwub6JOK54ZV3fuPUX8tI7f/eT6MFVNN75uDLZavgqz56obwK+8IXQxyx1KYl2PJJJNI3DcCuFOgu0M8zhoc2HjvoDoYgs16dFdpgb1iaSRm9YxgS9czhkxlEFaSxPhRI3MVHO5YFMvAJK2z8vzx4YOsPkHN2kWvNZCMBNhtsdOwDau2l5y8EE+ExRPwsBwQgoBqnTznZavCfDmL0YlV0r58S8R+aLqUU0VqYWgpS7gTk47uQh6x3zaFDacbZZc5Z4nDvNP+JjBEH0mGDPIIkTzwiS+/o9+G0ookMufXQEAFSuydRk6QZ+er1p0JZaBaKKsk1kOYf2Vcfd0LbifJgBZ3zuq83IoBI+7P9gLtFmCUxXGOy1iSkNZHEndufxX3aEIn6gGroDBo33p/0oEuRyvNrSXs5dtkWohdE3sMHJdoGgZV9TvPdvINtXm622ZzUSB2gu50/KVuHRIhPXk6A=
        distributions: sdist bdist_wheel
        on:
          tags: true
          repo: pytest-dev/pytest-metadata

cache: pip

install: pip install tox

script: tox
